var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/destinations/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__07naxj3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0erxv6~.js")
R.c("server/chunks/ssr/_00hffc7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0499wqt._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vgxo.h._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_destinations_page_actions_03nbp8d.js")
R.m(38909)
module.exports=R.m(38909).exports
