var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/destinations/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0h-o0f.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_135tebf.js")
R.c("server/chunks/ssr/_0viwpz3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0499wqt._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vgxo.h._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_destinations_[id]_page_actions_0o6q7bp.js")
R.m(76927)
module.exports=R.m(76927).exports
